CREATE DATABASE ItemMaster DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE ItemMaster;

CREATE TABLE Heroe (
	Id_heroe INT AUTO_INCREMENT NOT NULL,
	Nombre_heroe VARCHAR (100) NOT NULL,
	Tipo_heroe VARCHAR (100) NOT NULL,
    Raza_heroe VARCHAR (100) NOT NULL,
    Id_roll INT NOT NULL,
    Id_eqph INT NOT NULL,
	PRIMARY KEY(Id_heroe)
);

CREATE TABLE Arma_Grande (
	Id_armaG INT AUTO_INCREMENT NOT NULL,
	Nombre_arma VARCHAR (100) NOT NULL,
	Tipo_arma VARCHAR (100) NOT NULL,
	Nivel_arma VARCHAR (100) NOT NULL,
	PRIMARY KEY(Id_armaG)
);

CREATE TABLE Arma_Peq (
	Id_armaP INT AUTO_INCREMENT NOT NULL,
	Nombre_arma VARCHAR (100) NOT NULL,
	Tipo_arma VARCHAR (100) NOT NULL,
	Nivel_arma VARCHAR (100) NOT NULL,
	PRIMARY KEY(Id_armaP)
);

CREATE TABLE Roll (
	Id_roll INT AUTO_INCREMENT NOT NULL,
	Nombre_roll VARCHAR (100) NOT NULL,
	Tipo_roll VARCHAR (100) NOT NULL,
	Nivel_roll VARCHAR (100) NOT NULL,
	PRIMARY KEY(Id_roll)
);

CREATE TABLE Armadura (
	Id_armadura INT AUTO_INCREMENT NOT NULL,
	Nombre_armadura VARCHAR (100) NOT NULL,
	Tipo_armadura VARCHAR (100) NOT NULL,
	Nivel_armadura VARCHAR (100) NOT NULL,
	PRIMARY KEY(Id_armadura)
);

CREATE TABLE EQUIP_HEROE (
Id_eqph INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Id_cab INT NOT NULL,
Id_hom INT NOT NULL,
Id_pec INT NOT NULL,
Id_pie INT NOT NULL,
Id_bot INT NOT NULL,
Id_arma1 INT NOT NULL,
ID_arma2 INT NOT NULL
);

ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_1 FOREIGN KEY (Id_cab) REFERENCES Armadura (Id_armadura);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_2 FOREIGN KEY (Id_hom) REFERENCES Armadura (Id_armadura);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_3 FOREIGN KEY (Id_pec) REFERENCES Armadura (Id_armadura);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_4 FOREIGN KEY (Id_pie) REFERENCES Armadura (Id_armadura);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_5 FOREIGN KEY (Id_bot) REFERENCES Armadura (Id_armadura);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_6 FOREIGN KEY (Id_arma1) REFERENCES Arma_Grande (Id_armaG);
ALTER TABLE EQUIP_HEROE ADD CONSTRAINT a_7 FOREIGN KEY (Id_arma2) REFERENCES Arma_Peq (Id_armaP);

ALTER TABLE Heroe ADD CONSTRAINT h1 FOREIGN KEY (Id_roll) REFERENCES Roll (Id_roll);
ALTER TABLE Heroe ADD CONSTRAINT h2 FOREIGN KEY (Id_eqph) REFERENCES EQUIP_HEROE (Id_eqph);
